### PR TITLE
Applied the correct enabling and disabling of menu items.

### PR DESCRIPTION
**Pull request by arbreurkes**
Disabling and enabling of certain functions was off.

### CODE REVIEW

**Comment by arbreurkes** [comment]
Fixing faulty auto-merges first.

**Comment by arbreurkes** [comment]
Everything should now be fixed.

**Comment by ghost** [comment]
No code remarks

**Comment by tieswesterborg** [comment]
ready to merge

**Comment by dvantetering** [comment]
Looks fine, small enhancement

**Pull request merged**
