### PR TITLE
reduced method lengths in graphReducer, refactored addEdgesToCell

### PR DESCRIPTION
**Pull request by niekvanderlaan**
- Split up methods in GraphReducer
- Refactored addEdgesToCell

### CODE REVIEW

**Comment by skullyhoofd** [comment]
Looks good

**Comment by ric-jon** [comment]
Build failed, please fix this

**Comment by niekvanderlaan** [comment]
I have adapted the test classes, Travis seems to pass now

**Comment by tieswesterborg** [comment]
Looks good!

**Pull request merged**
