### PR TITLE
bug fixed

### PR DESCRIPTION
**Pull request by ric-jon**

### CODE REVIEW

**Comment by dvantetering** [comment]
fine by me, just wait for Travis and then merge

**Comment by dvantetering** [comment]
next time, specify the bug in the description of the PR

**Comment by ric-jon** [comment]
Next time, don't double post

**Comment by dvantetering** [comment]
shots fired

**Comment by tieswesterborg** [comment]
Ready to merge, if travis is ready

**Comment by dvantetering** [comment]
Ready to merge!

**Comment by tieswesterborg** [comment]
@dvantetering please wait for travis.

**Pull request merged**
