### PR TITLE
Added logical or filters in category and logical and filter inter-cat…

### PR DESCRIPTION
**Pull request by arbreurkes**
…egory. Also removed bug of showing active filters.

### CODE REVIEW

**Comment by dvantetering** [comment]
Please run maven site

**Comment by tieswesterborg** [comment]
Pls maven

**Comment by arbreurkes** [comment]
I ran maven.

**Comment by ghost** [comment]
ok

**Comment by dvantetering** [comment]
now fix it

**Comment by tieswesterborg** [comment]
FIX maven

**Comment by ric-jon** [comment]
There's norway there are no checkstyle problems

**Comment by ric-jon** [comment]
I hope when Jim reads this he won't denmark us down for this

**Comment by dvantetering** [comment]
Don't push it

**Comment by ric-jon** [comment]
Have you fixed maven yet? I'm not Ghana ask again.

**Comment by arbreurkes** [comment]
I'm from Italy, I don't know how I Canada do this

**Comment by ghost** [comment]
ok

**Comment by skullyhoofd** [comment]
I feel so much spain when I read these comments

**Comment by dvantetering** [comment]
https://www.youtube.com/watch?v=m1TnzCiUSI0

**Comment by skullyhoofd** [comment]
Take your time, don't be Russian it

**Comment by arbreurkes** [comment]
Check style is now fixed, CzeCH it out.

**Comment by arbreurkes** [comment]
If you want I can Samurais is for u

**Comment by tieswesterborg** [comment]
Jij gaat echt ja pan uit met deze grappen

**Pull request merged**
